CREATE TABLE [dbo].[QueueBuffer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ActiveQueueId] [int] NOT NULL,
	[CurrentQueuId] [int] NOT NULL,
	[CurrentQueueExpiration] [datetime] NOT NULL,
 CONSTRAINT [PK_QueueBuffer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]