CREATE TABLE [dbo].[QueueData]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[QueueID] [int] NOT NULL,
	[Data] [nvarchar](max) NOT NULL
 CONSTRAINT [PK_QueueData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
