CREATE TABLE [dbo].[LinkedInCompanies] (
    [Id]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [LinkedInCompanyId]          BIGINT         NULL,
    [LinkedInCompanyUrl]        NVARCHAR (255) NOT NULL,
    [LinkedInCompanyName] NVARCHAR (255) NULL,
    [DomainName]          NVARCHAR (255) NULL,
    [Specialties]         NVARCHAR (MAX) NULL,
    [StreetAddress]       NVARCHAR (255) NULL,
    [Locality]            NVARCHAR (50)  NULL,
    [Region]              NVARCHAR (50)  NULL,
    [PostalCode]          NVARCHAR (20)  NULL,
    [CountryName]         NVARCHAR (50)  NULL,
    [Website]             NVARCHAR (255) NULL,
    [Industry]            NVARCHAR (100) NULL,
    [CompanyType]                NVARCHAR (50)  NULL,
    [CompanySize]         NVARCHAR (25)  NULL,
    [Founded]             NVARCHAR (25)  NULL,
    [FollowersCount]      INT            NULL,
	[FollowUrl]            NVARCHAR (255) NULL,
    [PhotoUrl]            NVARCHAR (255) NULL,
    [CompanyDescription]         NVARCHAR (MAX) NULL,
    [CreatedDate]         DATETIME       NOT NULL,
    [UpdatedDate]         DATETIME       NOT NULL,
    CONSTRAINT [PK_LinkedInCompanies] PRIMARY KEY CLUSTERED ([Id] ASC)
);

