CREATE TABLE [dbo].[LinkedInCompanies] (
    [Id]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [LinkedInId]          BIGINT         NULL,
    [LinkedInPage]        NVARCHAR (255) NOT NULL,
    [LinkedInCompanyName] NVARCHAR (255) NULL,
    [DomainName]          NVARCHAR (255) NULL,
    [specialties]         NVARCHAR (MAX) NULL,
    [streetAddress]       NVARCHAR (255) NULL,
    [locality]            NVARCHAR (50)  NULL,
    [region]              NVARCHAR (50)  NULL,
    [postalCode]          NVARCHAR (20)  NULL,
    [countryName]         NVARCHAR (50)  NULL,
    [website]             NVARCHAR (255) NULL,
    [industry]            NVARCHAR (100) NULL,
    [type]                NVARCHAR (50)  NULL,
    [companySize]         NVARCHAR (25)  NULL,
    [founded]             NVARCHAR (25)  NULL,
    [followersCount]      INT            NULL,
    [photourl]            NVARCHAR (255) NULL,
    [description]         NVARCHAR (MAX) NULL,
    [CreatedDate]         DATETIME       NOT NULL,
    [UpdatedDate]         DATETIME       NOT NULL,
    CONSTRAINT [PK_LinkedInCompanies] PRIMARY KEY CLUSTERED ([Id] ASC)
);

