CREATE NONCLUSTERED INDEX [IX_QueueMeta_QueueName] ON [dbo].[QueueMeta]
(
	[QueueName] ASC,
	[Status] ASC
)
INCLUDE ([DequeueItemExpiration]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)