//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrakrData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkedInProfile()
        {
            this.UserLinkedInProfiles = new HashSet<UserLinkedInProfile>();
        }
    
        public long Id { get; set; }
        public Nullable<long> LinkedInProfileId { get; set; }
        public string LinkedInPage { get; set; }
        public string LinkedInFullName { get; set; }
        public Nullable<int> LinkedInConnections { get; set; }
        public string LinkedInTitle { get; set; }
        public string LinkedInCompanyName { get; set; }
        public Nullable<long> LinkedInCompanyId { get; set; }
        public string Industry { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public string IM { get; set; }
        public string Twitter { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string LinkedInPhotoUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLinkedInProfile> UserLinkedInProfiles { get; set; }
    }
}
