//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrakrData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInCompany
    {
        public long Id { get; set; }
        public Nullable<long> LinkedInId { get; set; }
        public string LinkedInPage { get; set; }
        public string LinkedInCompanyName { get; set; }
        public string DomainName { get; set; }
        public string specialties { get; set; }
        public string streetAddress { get; set; }
        public string locality { get; set; }
        public string region { get; set; }
        public string postalCode { get; set; }
        public string countryName { get; set; }
        public string website { get; set; }
        public string industry { get; set; }
        public string type { get; set; }
        public string companySize { get; set; }
        public string founded { get; set; }
        public Nullable<int> followersCount { get; set; }
        public string photourl { get; set; }
        public string description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AspNetUsers_Id { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
