//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrakrData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkedInCompany()
        {
            this.UserLinkedInCompanies = new HashSet<UserLinkedInCompany>();
        }
    
        public long Id { get; set; }
        public Nullable<long> LinkedInCompanyId { get; set; }
        public string LinkedInCompanyUrl { get; set; }
        public string LinkedInCompanyName { get; set; }
        public string DomainName { get; set; }
        public string Specialties { get; set; }
        public string StreetAddress { get; set; }
        public string Locality { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string CountryName { get; set; }
        public string Website { get; set; }
        public string Industry { get; set; }
        public string CompanyType { get; set; }
        public string CompanySize { get; set; }
        public string Founded { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public string FollowUrl { get; set; }
        public string PhotoUrl { get; set; }
        public string CompanyDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLinkedInCompany> UserLinkedInCompanies { get; set; }
    }
}
