//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrakrData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesForceAccount
    {
        public int Id { get; set; }
        public string SfClientId { get; set; }
        public string SfClientSecret { get; set; }
        public string SfUsername { get; set; }
        public string SfPassword { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
