//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTrakrData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLinkedInProfile
    {
        public long Id { get; set; }
        public long LinkedInProfileId { get; set; }
        public string AspNetUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LinkedInProfile LinkedInProfile { get; set; }
    }
}
