namespace NetSuite.RESTlet.Integration.Search
{
    public enum NsSearchRecordType
    {
        // ReSharper disable InconsistentNaming
        account 
        ,accountingPeriod 
        ,appDefinition 
        ,appPackage 
        ,assemblyItem 
        ,bin 
        ,budget 
        ,calendarEvent 
        ,campaign 
        ,classification 
        ,contact 
        ,customer 
        ,customerMessage 
        ,customRecord 
        ,department 
        ,employee 
        ,entityGroup 
        ,file 
        ,folder 
        ,giftCertificate 
        ,groupMember 
        ,inventoryNumber 
        ,item 
        ,issue 
        ,job 
        ,location 
        ,lotNumberedAssemblyItem 
        ,manufacturingCostTemplate 
        ,manufacturingOperationTask 
        ,manufacturingRouting 
        ,message 
        ,nexus 
        ,note 
        ,opportunity 
        ,otherNameCategory 
        ,partner 
        ,phoneCall 
        ,priceLevel 
        ,pricingGroup 
        ,projectTask 
        ,promotionCode 
        ,resourceAllocation 
        ,revRecSchedule 
        ,revRecTemplate 
        ,salesRole 
        ,serializedAssemblyItem 
        ,solution 
        ,siteCategory 
        ,subsidiary 
        ,supportCase 
        ,task 
        ,timeBill 
        ,topic 
        ,transaction 
        ,vendor
        // ReSharper restore InconsistentNaming
    }
}